name: Start VM

on: workflow_dispatch

jobs:
  start-vm:
    runs-on: ubuntu-latest
    steps:
      - name: Azure Login
        uses: Azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: Azure CLI Script
        uses: azure/CLI@v2
        with:
          azcliversion: 2.30.0
          inlineScript: |
            az vm start --resource-group ${{ secrets.VM_RESOURCE_GROUP }} --name ${{ secrets.VM_NAME }}
